logo_title: ShoJinTO

style: black

favicon: /favicon.ico

menu:
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about
  Github: https://github.com/shojinto

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: sBc8tGpQjtwbggV9gG8iVW1b-gzGzoHsz
  appKey: 95egYUoH984IghLnWsu0eyA6

highlight:
  enable: false
  
# Analytics
baidu_analytics: 
  enable: true
  appId: 72885fc2764dfa73d0ab5176af60d0d1
